/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Image;
import java.io.File;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author DELL
 */
public class frmVer extends javax.swing.JFrame {

    /**
     * Creates new form frmVer
     */
    
    Nodo aux = Principal.inicio;
    static int index = 0;
    static JFileChooser explorador = new JFileChooser();
    
    
    public frmVer() {
        initComponents();
        if (aux != null) //Primer nodo
        {
            visualizarNodo(lblCodigo1,lblNombre1,lblEdad1,lblFrase1,lblFoto1);
            aux = aux.getSiguiente();
            if (aux != null) // Segundo nodo
            {   
              visualizarNodo(lblCodigo2,lblNombre2,lblEdad2,lblFrase2,lblFoto2);
              aux = aux.getSiguiente();  
            }
            if (aux != null) // Tercer nodo
            {
              visualizarNodo(lblCodigo3,lblNombre3,lblEdad3,lblFrase3,lblFoto3);
              aux = aux.getSiguiente();  
            }
            if (aux != null) //Cuarto nodo (aqui se queda)
            {
              visualizarNodo(lblCodigo4,lblNombre4,lblEdad4,lblFrase4,lblFoto4);
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnAnterio = new javax.swing.JButton();
        lblNombre1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblFoto3 = new javax.swing.JLabel();
        lblFoto4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblFoto1 = new javax.swing.JLabel();
        lblEdad1 = new javax.swing.JLabel();
        lblFrase1 = new javax.swing.JLabel();
        lblNombre2 = new javax.swing.JLabel();
        lblEdad2 = new javax.swing.JLabel();
        lblFrase2 = new javax.swing.JLabel();
        lblFrase4 = new javax.swing.JLabel();
        lblEdad4 = new javax.swing.JLabel();
        lblNombre4 = new javax.swing.JLabel();
        lblFrase3 = new javax.swing.JLabel();
        lblEdad3 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lblCodigo1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblCodigo2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblCodigo3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblCodigo4 = new javax.swing.JLabel();
        btnRegresar1 = new javax.swing.JButton();
        buscadorTxt = new javax.swing.JTextField();

        lblFoto2.setBackground(new java.awt.Color(255, 255, 255));
        lblFoto2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFoto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto2.setText("Sin foto");
        lblFoto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFoto2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFoto2.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Edad:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Frase:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Ver anuario");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Edad:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Frase:");

        btnSiguiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSiguiente.setMnemonic('s');
        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAnterio.setMnemonic('r');
        btnAnterio.setText("<");
        btnAnterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnterioActionPerformed(evt);
            }
        });

        lblNombre1.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre1.setText("\"\"");
        lblNombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNombre1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNombre1.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Nombre:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Edad:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Frase:");

        lblFoto3.setBackground(new java.awt.Color(255, 255, 255));
        lblFoto3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFoto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto3.setText("Sin foto");
        lblFoto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFoto3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFoto3.setOpaque(true);

        lblFoto4.setBackground(new java.awt.Color(255, 255, 255));
        lblFoto4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFoto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto4.setText("Sin foto");
        lblFoto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFoto4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFoto4.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Nombre:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Edad:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Frase:");

        lblFoto1.setBackground(new java.awt.Color(255, 255, 255));
        lblFoto1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto1.setText("Sin foto");
        lblFoto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFoto1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFoto1.setOpaque(true);

        lblEdad1.setBackground(new java.awt.Color(255, 255, 255));
        lblEdad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEdad1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEdad1.setText("\"\"");
        lblEdad1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEdad1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEdad1.setOpaque(true);

        lblFrase1.setBackground(new java.awt.Color(255, 255, 255));
        lblFrase1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFrase1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFrase1.setText("\"\"");
        lblFrase1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblFrase1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFrase1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFrase1.setOpaque(true);

        lblNombre2.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre2.setText("\"\"");
        lblNombre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNombre2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNombre2.setOpaque(true);

        lblEdad2.setBackground(new java.awt.Color(255, 255, 255));
        lblEdad2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEdad2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEdad2.setText("\"\"");
        lblEdad2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEdad2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEdad2.setOpaque(true);

        lblFrase2.setBackground(new java.awt.Color(255, 255, 255));
        lblFrase2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFrase2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFrase2.setText("\"\"");
        lblFrase2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblFrase2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFrase2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFrase2.setOpaque(true);

        lblFrase4.setBackground(new java.awt.Color(255, 255, 255));
        lblFrase4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFrase4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFrase4.setText("\"\"");
        lblFrase4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblFrase4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFrase4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFrase4.setOpaque(true);

        lblEdad4.setBackground(new java.awt.Color(255, 255, 255));
        lblEdad4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEdad4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEdad4.setText("\"\"");
        lblEdad4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEdad4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEdad4.setOpaque(true);

        lblNombre4.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre4.setText("\"\"");
        lblNombre4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNombre4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNombre4.setOpaque(true);

        lblFrase3.setBackground(new java.awt.Color(255, 255, 255));
        lblFrase3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFrase3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFrase3.setText("\"\"");
        lblFrase3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblFrase3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFrase3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFrase3.setOpaque(true);

        lblEdad3.setBackground(new java.awt.Color(255, 255, 255));
        lblEdad3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEdad3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEdad3.setText("\"\"");
        lblEdad3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblEdad3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEdad3.setOpaque(true);

        lblNombre3.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre3.setText("\"\"");
        lblNombre3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNombre3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNombre3.setOpaque(true);

        btnRegresar.setBackground(new java.awt.Color(255, 255, 102));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegresar.setMnemonic('e');
        btnRegresar.setText("<");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Código:");

        lblCodigo1.setBackground(new java.awt.Color(255, 255, 255));
        lblCodigo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodigo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo1.setText("\"\"");
        lblCodigo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCodigo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCodigo1.setOpaque(true);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Código:");

        lblCodigo2.setBackground(new java.awt.Color(255, 255, 255));
        lblCodigo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodigo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo2.setText("\"\"");
        lblCodigo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCodigo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCodigo2.setOpaque(true);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Código:");

        lblCodigo3.setBackground(new java.awt.Color(255, 255, 255));
        lblCodigo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodigo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo3.setText("\"\"");
        lblCodigo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCodigo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCodigo3.setOpaque(true);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Código:");

        lblCodigo4.setBackground(new java.awt.Color(255, 255, 255));
        lblCodigo4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodigo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCodigo4.setText("\"\"");
        lblCodigo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCodigo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCodigo4.setOpaque(true);

        btnRegresar1.setBackground(new java.awt.Color(204, 204, 255));
        btnRegresar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegresar1.setText("Buscar");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(6, 6, 6)
                                .addComponent(lblNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(6, 6, 6)
                                .addComponent(lblEdad2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(lblFrase2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(lblFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(6, 6, 6)
                                .addComponent(lblNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(12, 12, 12)
                                .addComponent(lblEdad4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)
                            .addComponent(lblFrase4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnterio)
                        .addGap(960, 960, 960)
                        .addComponent(btnSiguiente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addComponent(lblEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(lblFrase1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(lblFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(6, 6, 6)
                                .addComponent(lblNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(6, 6, 6)
                                .addComponent(lblEdad3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addComponent(lblFrase3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(386, 386, 386)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar1)
                        .addGap(30, 30, 30)
                        .addComponent(buscadorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnRegresar1)
                            .addComponent(buscadorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(lblCodigo1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(lblNombre1)))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(lblEdad1)))
                            .addGap(6, 6, 6)
                            .addComponent(jLabel5)
                            .addGap(12, 12, 12)
                            .addComponent(lblFrase1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(lblCodigo3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(lblNombre3)))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(lblEdad3)))
                            .addGap(6, 6, 6)
                            .addComponent(jLabel11)
                            .addGap(6, 6, 6)
                            .addComponent(lblFrase3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lblCodigo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblNombre2)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblEdad2)))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(lblFrase2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(lblCodigo4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblNombre4)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblEdad4)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(12, 12, 12)
                        .addComponent(lblFrase4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnterio)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnSiguiente))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        RecDerecha();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        /*
        if(vr.getUser() == ("Admin1") || vr.getPassword() ==("contrasena")){
            Principal rtn = new Principal();
            rtn.setVisible(true);
            this.setVisible(false);
        }else
        */
        Principal rtn = new Principal();
        rtn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAnterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterioActionPerformed
        RecIzquierda();
    }//GEN-LAST:event_btnAnterioActionPerformed

    /**
     * @param item
     * @return middle  || -1
     * Descripcion: se le ingresa un codigo y regresa el index del codigo en el array de la clase ArrayObjetos
     * si es que se encuentra, ese index 
     */
    public static int binarySearch(int item) {
        int low = 0;
        int high = frmIngresar.array.length - 1;

        while (low <= high) {
            int middle = (low + high) / 2;
            if (frmIngresar.array[middle].codigos == item) {
                return middle;
            } else if (frmIngresar.array[middle].codigos < item) {
                low = middle + 1;
            } else {
                high = middle - 1;
            }
        }
        
        return -1;
    }
    
    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        buscadorTxt.getText();
        index = binarySearch(Integer.parseInt(buscadorTxt.getText()));

        // Si el número se encontró, mostramos su índice y activamos la pagina buscador
        if (index != -1) {
            buscadorTxt.setText("");
            Buscador rtn = new Buscador();
            rtn.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "no existe ese codigo");
        }
        buscadorTxt.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVer().setVisible(true);
            }
        });
    }
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JTextField buscadorTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCodigo1;
    private javax.swing.JLabel lblCodigo2;
    private javax.swing.JLabel lblCodigo3;
    private javax.swing.JLabel lblCodigo4;
    private javax.swing.JLabel lblEdad1;
    private javax.swing.JLabel lblEdad2;
    private javax.swing.JLabel lblEdad3;
    private javax.swing.JLabel lblEdad4;
    private javax.swing.JLabel lblFoto1;
    private javax.swing.JLabel lblFoto2;
    private javax.swing.JLabel lblFoto3;
    private javax.swing.JLabel lblFoto4;
    private javax.swing.JLabel lblFrase1;
    private javax.swing.JLabel lblFrase2;
    private javax.swing.JLabel lblFrase3;
    private javax.swing.JLabel lblFrase4;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombre4;
    // End of variables declaration//GEN-END:variables
    /**
     * 
     * @param ruta_imagen Ruta de la imagen guardada
     * @param lbl Nombre de la etiqueta
     */
    void Mostrar_imagen(String ruta_imagen, JLabel lbl){
        try{
            if(Principal.fin==null){
                lbl.setText("Lista vacia");
                lbl.setIcon(null);
                }else{    
                ImageIcon foto;
                foto = new ImageIcon(ruta_imagen);
                Icon icono;
                icono = new ImageIcon(foto.getImage()
                .getScaledInstance(lbl.getWidth(),lbl.getHeight()
                ,Image.SCALE_DEFAULT));//adapatación al tamaño de la etiqueta
                lbl.setIcon(icono);
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,
                "Error al abrir el archivo","Advertencia",
                JOptionPane.WARNING_MESSAGE);
            }
    }
    /**
     * 
     * @param codigo Ingresa el nombre del la etiqueta de codigo
     * @param nombre Inngresa el nombre de la etiqueta para nombre
     * @param edad Ingresa el nombre de la etiqueta para edad
     * @param frase Inngresa el nombre de la etiqueta para frase
     * @param foto  Ingresa el nombre de la etiqueta para foto
     * 
     * Toma la informacion actual de auxiliar y lo ingresa a las etiquetas
     */
    void visualizarNodo(JLabel codigo,JLabel nombre, JLabel edad,JLabel frase,JLabel foto)
    {
        codigo.setText(String.valueOf(aux.getCodigo()));
        nombre.setText(aux.getNombre());
        edad.setText(aux.getEdad());
        frase.setText(aux.getFrase());
        Mostrar_imagen(aux.getRutaImagen(),foto);
        foto.setText("");
    }
    
    
    void RecDerecha()
    {
        if(aux.getSiguiente()==null){
            JOptionPane.showMessageDialog(null,"No hay más alumnos registrados");
           this.btnSiguiente.setVisible(false);
        }else
        {
           /*Nota: 
            * El visualizarNodo trabaja con la posicion actual de auxiliar
            * Habra movimientos constantes de auxiliar
            */ 
            
           //Ingresa la informacion del nodo 4 en el espacio 2
           visualizarNodo(lblCodigo2,lblNombre2,lblEdad2,lblFrase2,lblFoto2);
           aux = aux.getAnterior(); //auxiliar toma la informacion del nodo 3
           //Ingresa la informacion del nodo 3 en el espacio 1
           visualizarNodo(lblCodigo1,lblNombre1,lblEdad1,lblFrase1,lblFoto1);
           
           // Ahora nodo toma la informacion del nodo 5
           aux = aux.getSiguiente().getSiguiente();
           //Ingresa la informacion del nodo 5 en el espacio 3
           visualizarNodo(lblCodigo3,lblNombre3,lblEdad3,lblFrase3,lblFoto3);
            if (aux.getSiguiente() == null) //Revisa que haya informacion en el nodo 6
            { //Si no hay informacion, deja todo vacio
                lblCodigo4.setText("NR");
                lblNombre4.setText("NR");
                lblEdad4.setText("NR");
                lblFrase4.setText("NR");
                lblFoto4.setIcon(null);
                lblFoto4.setText("Sin foto");
                this.btnSiguiente.setVisible(false);
            }else
            {
                aux=aux.getSiguiente();//se queda con la informacion del nodo 6
                visualizarNodo(lblCodigo4,lblNombre4,lblEdad4,lblFrase4,lblFoto4);
            }
        }              
    }
    void RecIzquierda()
    {
            // ** Espacio 4 **
            aux = aux.getAnterior().getAnterior(); //Se dirige hasta el segundo nodo
            visualizarNodo(lblCodigo4,lblNombre4,lblEdad4,lblFrase4,lblFoto4); //Lo visualiza en el nodo 4
            // ** Espacio 3 **
            aux = aux.getAnterior(); // Se dirige al primer nodo
            visualizarNodo(lblCodigo3,lblNombre3,lblEdad3,lblFrase3,lblFoto3); //Lo visualiza en el nodo 3
            // ** Espacio 2 **
            aux = aux.getAnterior(); // Obtiene el que esta detras del primer nodo
            visualizarNodo(lblCodigo2,lblNombre1,lblEdad2,lblFrase2,lblFoto2); // Lo visualiza en el espacio 2
            // ** Espacio 1 **
            aux = aux.getAnterior(); // Obtiene una posicion una mas atras
            visualizarNodo(lblCodigo1,lblNombre1,lblEdad1,lblFrase1,lblFoto1); // Lo visualiza en el espacio 1
            this.btnSiguiente.setVisible(true);
            aux = aux.getSiguiente().getSiguiente().getSiguiente(); // Regresa a su posicion inicial
    }
    /*
    public void getVistaFoto1(){
        //lblCodigo1.setText();
        lblNombre1.setText(aux.getNombre());
        lblEdad1.setText(aux.getEdad());
        lblFrase1.setText(aux.getFrase());
        Mostrar_imagen(aux.getRutaImagen());
        lblFoto5.setText("");
    }
    
    public void getVistaFoto2(){
        aux = aux.getSiguiente();
        lblNombre1.setText(aux.getNombre());
        lblEdad1.setText(aux.getEdad());
        lblFrase1.setText(aux.getFrase());
        Mostrar_imagen(aux.getRutaImagen());
        lblFoto5.setText("");
    }
    
    public void getVistaFoto3(){
        aux = aux.getSiguiente();
        lblNombre2.setText(aux.getNombre());
        lblEdad2.setText(aux.getEdad());
        lblFrase2.setText(aux.getFrase());
        Mostrar_imagen(aux.getRutaImagen());
        lblFoto5.setText("");
    }
    
    public void getVistaFoto4(){
        siguiente = aux.getSiguiente();
        lblNombre1.setText(siguiente.getNombre());
        lblEdad1.setText(siguiente.getEdad());
        lblFrase1.setText(siguiente.getFrase());
        Mostrar_imagen(siguiente.getRutaImagen());
        lblFoto3.setText("");
    }*/
}
