package practica5;

import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static practica5.Insertar.auxiliar;
import static practica5.Insertar.cabeza;
import static practica5.Insertar.contador;
import static practica5.Insertar.dirtmp;
import static practica5.Insertar.explorador;
import static practica5.Insertar.inicio;
import static practica5.Insertar.nuevo;

/**
 *
 * @author victo
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        JCodigo.setText(inicio.getCodigo());
        mostrarImagen(inicio.getRutaImagen());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btIzquierda = new javax.swing.JButton();
        btDerecha = new javax.swing.JButton();
        labNombre = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        JCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btIzquierda.setText("<");
        btIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIzquierdaActionPerformed(evt);
            }
        });

        btDerecha.setText(">");
        btDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDerechaActionPerformed(evt);
            }
        });

        labNombre.setText("Nombre");

        imagen.setText("Sin imagen");

        jLabel3.setText("Generacion de cristal");

        btRegresar.setText("Regresar");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labNombre)
                .addGap(31, 31, 31)
                .addComponent(JCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRegresar)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btIzquierda)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(162, 162, 162)
                        .addComponent(btDerecha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(imagen)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labNombre)
                            .addComponent(JCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btIzquierda)
                            .addComponent(btDerecha)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btRegresar)))
                .addGap(96, 96, 96)
                .addComponent(imagen)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static void mostrar() {
        if (cabeza != null) {
            nuevo = cabeza;
            while (nuevo != null) {
                System.out.println(nuevo.getCodigo());
                nuevo.getRutaImagen();
                //nuevo.setSiguiente(cabeza);
                nuevo = nuevo.getSiguiente();
            }
        } else {
            System.out.println("la lista esta vacia");
        }
    }
    
    void mostrarImagen(String dirImg) {
        ImageIcon foto;
       foto = new ImageIcon(dirImg);
       Icon icono;
       icono = new ImageIcon(foto.getImage().getScaledInstance(480,320, Image.SCALE_DEFAULT));
       imagen.setText(" ");
       imagen.setIcon(icono);
       System.out.println(auxiliar);
    }
    
    
    
    void insertarFoto(String dirImg) {
         try{
             
             mostrarImagen(dirtmp);
             mostrar();
         } catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "error al abrir el archivo", "advertencia", JOptionPane.WARNING_MESSAGE);
         }
    }
    
    private void btIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIzquierdaActionPerformed
        if (auxiliar == null) {
                auxiliar = cabeza;
                JCodigo.setText(auxiliar.getCodigo());
                mostrarImagen(auxiliar.getRutaImagen());
            } else {
                auxiliar = auxiliar.getAnterior();
                JCodigo.setText(auxiliar.getCodigo());
                mostrarImagen(auxiliar.getRutaImagen());
            }
    }//GEN-LAST:event_btIzquierdaActionPerformed

    private void btDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDerechaActionPerformed
            if (auxiliar == null) {
                auxiliar = cabeza;
                JCodigo.setText(auxiliar.getCodigo());
                mostrarImagen(auxiliar.getRutaImagen());
            } else {
                auxiliar = auxiliar.getSiguiente();
                JCodigo.setText(auxiliar.getCodigo());
                mostrarImagen(auxiliar.getRutaImagen());
            }
    }//GEN-LAST:event_btDerechaActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        Main ventana = new Main();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JCodigo;
    private javax.swing.JButton btDerecha;
    private javax.swing.JButton btIzquierda;
    private javax.swing.JButton btRegresar;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labNombre;
    // End of variables declaration//GEN-END:variables
}